

default:
	g++ -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL -Llib -Iinclude -lraylib main.cpp game.cpp graphics.cpp controls.cpp neighborhood.cpp button.cpp rules.cpp -o ex

clean:
	rm -f ex

	