

default:

	g++ -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL -Llib -Iinclude -lraylib main.cpp game.cpp paddle.cpp ball.cpp sounds.cpp graphics.cpp -o ex.exe
